[project]
name = "InfoGene"
dynamic = ["dependencies"]
version = "0.1.0"
description = "A web application for searching HGNC gene information"
authors = [{name = "Nathania Kulkarni", email = "nathania.kulkarni@postgrad.manchester.ac.uk" }]
readme = "README.md"
keywords = ["gene", "search", "HGNC", "web application"]
requires-python = ">=3.12"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[tool.setuptools.packages.find]
where = ["."]
include = ["InfoGene*"]

[build-system]
requires = ["setuptools>=77", "wheel"]
build-backend = "setuptools.build_meta"